name: Build and Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Binaries
        run: |
          mkdir -p ./bin
          # Build all Go binaries and output them into ./bin/
          GOOS=windows GOARCH=amd64 go build -o ./bin/ ./...

      - name: Collect Binaries
        id: collect_binaries
        run: |
          # Rename all .exe files in ./bin/ to include the version (release tag)
          for bin in ./bin/*.exe; do
            # Get the base name of the binary (e.g., 'alliteration' from 'alliteration.exe')
            base_name=$(basename "$bin" .exe)
            # Rename the binary to include the release version (tag)
            mv "$bin" "./bin/${base_name}-${{ github.event.release.tag_name }}.exe"
          done
          
          # Collect all renamed .exe files from ./bin/
          binary_files=$(find ./bin -name "*.exe" -print | tr '\n' ' ')
          echo "binary_files=$binary_files" >> $GITHUB_ENV

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.binary_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
